---
- name: Install Docker (if required)
  hosts: spark_nodes
  tasks:
    - name: Check if Docker Compose is available
      command: docker compose version
      register: docker_compose_check
      failed_when: false
      changed_when: false
    - name: Install Docker
      include_role:
        name: rhel-install-docker
      when: docker_compose_check.rc != 0
    - name: Install pip
      become: true
      dnf:
        name: python3-pip
        state: present
    - name: Install docker Python library
      become: true
      pip:
        name: docker
        state: present
- import_playbook: setup-swarm-cluster.yaml
