- name: Check if CIS benchmark report is ready
  command: test -f cis-report.html
  register: cis_benchmark_report_check
  failed_when: false
  changed_when: false
- include_tasks: rhel9.yml
  when: cis_benchmark_report_check.rc != 0
