---
# See: https://docs.docker.com/engine/install/rhel/
- name: Install dnf-plugins-core package
  become: true
  dnf:
    name: dnf-plugins-core
    state: present
- name: Add Docker repository
  become: true
  shell:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
- name: Install Docker
  become: true
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
