---
- name: Ensure CIS benchmark compliance on hosts
  hosts: all
  become: true
  tasks:
    - name: Ensure user password
      user:
        name: "{{ ansible_user }}"
        password: "{{ ansible_become_password | password_hash('sha512', lookup('community.general.random_string', length=16, special=false)) }}"
    - name: Set root user password
      user:
        name: root
        password: "{{ lookup('ansible.builtin.password', '/dev/null', length=15, seed='ansible.root.password') | password_hash('sha512', lookup('community.general.random_string', length=16, special=false)) }}"
    - name: Add user to sudoers
      community.general.sudoers:
        name: "{{ ansible_user }}"
        user: "{{ ansible_user }}"
        commands: ALL
    - name: Restrict SSH /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "AllowUsers {{ ansible_user }}"
        state: present
      notify:
        - Restart sshd
    - name: Install OpenSCAP
      package:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present
    - name: Run OpenSCAP
      command: oscap xccdf eval --remediate --profile xccdf_org.ssgproject.content_profile_cis --report cis-report.html /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      ignore_errors: true
  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
