all:
  vars:
    ansible_user: ec2-user
    ansible_python_interpreter: /usr/bin/python3
  children:
    spark_nodes:
      vars:
        swarm_interface: eth0
      children:
        spark_main_node:
          hosts:
            ec2-54-179-146-70.ap-southeast-1.compute.amazonaws.com:
        spark_worker_nodes:
          hosts:
            ec2-18-143-149-189.ap-southeast-1.compute.amazonaws.com:
            ec2-54-255-199-16.ap-southeast-1.compute.amazonaws.com:
