all:
  vars:
    ansible_user: ec2-user
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_password: "{{ lookup('password', '/dev/null', length=24, seed='mobicom-lakehouse.sudo.password') }}"
    root_password: "{{ lookup('password', '/dev/null', length=24, seed='mobicom-lakehouse.root.password') }}"
    network_interface: eth0
  children:
    spark_nodes:
      vars:
        spark_image: 122610515913.dkr.ecr.ap-southeast-1.amazonaws.com/yarn-spark:latest
      children:
        spark_main_node:
          hosts:
            ip-10-0-4-72.ap-southeast-1.compute.internal:
        spark_worker_nodes:
          hosts:
            ip-10-0-4-128.ap-southeast-1.compute.internal:
            ip-10-0-4-4.ap-southeast-1.compute.internal:
    atlas_nodes:
      hosts:
        ip-10-0-4-162.ap-southeast-1.compute.internal:
    airflow_nodes:
      vars:
        airflow:
          username: airflow
          password: "{{ lookup('password', '/dev/null', length=24, seed='mobicom-lakehouse.airflow.password') }}"
      hosts:
        ip-10-0-4-133.ap-southeast-1.compute.internal:
