---
- name: Setup Airflow nodes
  hosts: airflow_nodes
  tasks:
    - debug:
        var: airflow.password
    - include_role:
        name: cis-benchmark
    - include_role:
        name: install-docker
    - name: Ensure docker service is running
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install git
      become: true
      package:
        name: git
        state: present
    - name: Clone lakehouse repository
      become: true
      block:
        - name: Prepare directory for project
          file:
            path: /opt
            state: directory
        - name: Copy deployment key
          copy:
            # See: https://github.com/ansible/ansible/issues/30829#issuecomment-334192427
            content: "{{ lookup('file', 'files/deploy-key') + '\n' }}"
            dest: /tmp/lakehouse-deployment-key
            mode: 0600
        - name: Clone repository
          git:
            repo: git@github.com:erdenebayrd/mobicom.git
            key_file: /tmp/lakehouse-deployment-key
            accept_hostkey: true
            single_branch: true
            version: vpc-deployment
            dest: /opt/mobicom
        - name: Remove deployment key
          shell: shred -u /tmp/lakehouse-deployment-key
    - name: Configure dotenv file
      become: true
      template:
        src: files/airflow.env.j2
        dest: /opt/mobicom/.env
    - name: Set up logs directory
      become: true
      file:
        path: /opt/mobicom/.docker/airflow/logs
        mode: "0777"
        state: directory
    - name: Start Airflow
      become: true
      community.docker.docker_compose_v2:
        project_src: /opt/mobicom/.docker/airflow
