---
- name: Get Spark primary node address
  hosts: spark_main_node
  gather_facts: true
  tasks:
    - name: Set Spark primary node address
      set_fact:
        spark_main_node_address: "{{ ansible_facts[network_interface]['ipv4']['address'] }}"
- name: Setup Airflow nodes
  hosts: airflow_nodes
  tasks:
    - include_role:
        name: cis-benchmark
    - include_role:
        name: install-docker
    - name: Add Spark primary node to /etc/hosts
      become: true
      vars:
        spark_main_node_address: "{{ hostvars[groups['spark_main_node'][0]]['spark_main_node_address'] }}"
      lineinfile:
        dest: /etc/hosts
        regexp: ".* spark.internal$"
        line: "{{ spark_main_node_address }} spark.internal"
        state: present
    - name: Install git
      become: true
      package:
        name: git
        state: present
    - name: Clone lakehouse repository
      become: true
      block:
        - name: Prepare directory for project
          file:
            path: /opt
            state: directory
        - name: Copy deployment key
          copy:
            # See: https://github.com/ansible/ansible/issues/30829#issuecomment-334192427
            content: "{{ lookup('file', 'files/deploy-key') + '\n' }}"
            dest: /tmp/lakehouse-deployment-key
            mode: 0600
        - name: Clone repository
          git:
            repo: git@github.com:erdenebayrd/mobicom.git
            key_file: /tmp/lakehouse-deployment-key
            accept_hostkey: true
            single_branch: true
            version: vpc-deployment
            dest: /opt/mobicom
        - name: Remove deployment key
          shell: shred -u /tmp/lakehouse-deployment-key
    - name: Configure dotenv file
      become: true
      template:
        src: files/airflow.env.j2
        dest: /opt/mobicom/.env
    - name: Set up logs directory
      become: true
      file:
        path: /opt/mobicom/.docker/airflow/logs
        mode: "0777"
        state: directory
    - name: Start Airflow
      become: true
      community.docker.docker_compose_v2:
        project_src: /opt/mobicom/.docker/airflow
