---
- name: Setup Wireguard
  hosts: wg_bastion
  tasks:
    - name: Install wireguard-tools and iptables
      become: true
      package:
        name:
          - wireguard-tools
          - iptables
        state: present
    - name: Prepare host key directory
      become: true
      file:
        path: /etc/wireguard
        state: directory
    - name: Check if host private key exists
      become: true
      stat:
        path: /etc/wireguard/host.private.key
      register: host_private_key_file
    - name: Geneate host private key
      become: true
      shell: wg genkey | tee host.private.key
      args:
        chdir: /etc/wireguard
        creates: host.private.key
    - name: Set permissions on private key file
      become: true
      file:
        path: /etc/wireguard/host.private.key
        mode: "0600"
    - name: Enable IPv4 forwarding
      become: true
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: true
    - name: Copy wg0 interface config
      become: true
      template:
        src: templates/wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
      notify: Restart Wireguard
    - name: Set permissions for wg0 interface config
      become: true
      file:
        path: /etc/wireguard/wg0.conf
        mode: "0600"
  handlers:
    - name: Restart Wireguard
      become: true
      systemd:
        name: wg-quick@wg0
        state: restarted
        enabled: true
