---
- name: Configure nodes
  hosts: spark_nodes
  tasks:
    - include_role:
        name: cis-benchmark
    - name: Mount /dev/sdb into /opt/app
      become: true
      mount:
        path: /opt/app
        src: /dev/sdb
        fstype: ext4
        state: present
    - include_role:
        name: install-docker
    - name: Install ECR credentials helper
      become: true
      vars:
        version: 0.9.1
        checksums:
          arm64: sha256:a10012acfe5e28d7aed18f06bec4aa2a13fb3d9765898c36ef31136b24bd56e9
          amd64: sha256:c0054f2635b2f01b00f7bf6f88023ffe7fded15c533a85a493037607135eebac
      get_url:
        url: https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/{{ version }}/linux-{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}/docker-credential-ecr-login
        dest: /usr/bin/docker-credential-ecr-login
        mode: "0755"
        checksum: "{{ checksums['arm64' if ansible_facts.architecture == 'aarch64' else 'amd64'] }}"
    - name: Create directory for Docker configuration
      become: true
      file:
        path: /root/.docker
        state: directory
    - name: Setup Docker configuration
      become: true
      copy:
        content: |
          {
            "credsStore": "ecr-login"
          }
        dest: /root/.docker/config.json
    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install pip
      become: true
      dnf:
        name: python3-pip
        state: present
    - name: Install Python dependencies
      become: true
      pip:
        name:
          - docker
          - jsondiff
        state: present
    - name: Pull Spark image
      become: true
      docker_image:
        name: "{{ spark_image }}"
        source: pull
- import_playbook: playbooks/setup-swarm-cluster.yaml
- name: Setup Spark
  hosts: spark_main_node
  tasks:
    - name: Get primary node ID
      become: true
      # See: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_advanced_syntax.html#unsafe-or-raw-strings
      command: !unsafe docker node ls -f role=manager --format {{.ID}}
      register: primary_node_id
    - name: Set primary node Spark role
      become: true
      docker_node:
        hostname: "{{ primary_node_id.stdout }}"
        labels:
          spark-role: master
    - name: Get worker node IDs
      become: true
      command: !unsafe docker node ls -f role=worker --format {{.ID}}
      register: worker_node_ids
    - name: Set worker node Spark role
      become: true
      docker_node:
        hostname: "{{ item }}"
        labels:
          spark-role: worker
      with_items: "{{ worker_node_ids.stdout_lines }}"
    - name: Create directory for Spark configuration
      become: true
      file:
        path: /opt/app/spark
        state: directory
        recurse: true
    - name: Copy Spark stack config
      become: true
      template:
        src: files/spark-stack.yml.j2
        dest: /opt/app/spark/spark-stack.yml
    - name: Start Spark stack
      become: true
      docker_stack:
        state: present
        name: spark
        compose: [/opt/app/spark/spark-stack.yml]
